const express = require('express');
const session = require('express-session');
const oracledb = require('oracledb');
const { MongoClient } = require('mongodb');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 3001;
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static('public'));
app.use(session({ secret: process.env.SESSION_SECRET || 'secret', resave: false, saveUninitialized: false }));

let oraclePool, mongoDb, logsCol;

async function initDB() {
    try {
        oraclePool = await oracledb.createPool({
            user: process.env.ORACLE_USER,
            password: process.env.ORACLE_PASSWORD,
            connectString: process.env.ORACLE_CONNECT_STRING,
            poolMin: 2,
            poolMax: 5
        });
        
        const connection = await oraclePool.getConnection();
        try {
            await connection.execute(`CREATE TABLE users (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100),
                email VARCHAR2(100) UNIQUE,
                phone VARCHAR2(20),
                password VARCHAR2(100),
                is_admin NUMBER(1) DEFAULT 0
            )`);
            await connection.execute(`CREATE TABLE complaints (
                complaint_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER,
                title VARCHAR2(200),
                category VARCHAR2(50),
                priority VARCHAR2(20),
                status VARCHAR2(20) DEFAULT 'Pending',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY(user_id) REFERENCES users(id)
            )`);
            
            const result = await connection.execute('SELECT * FROM users WHERE is_admin = 1');
            if (result.rows.length === 0) {
                await connection.execute(`INSERT INTO users (id, name, email, phone, password, is_admin) 
                    VALUES (1, 'Admin', 'admin@system.com', '1234567890', 'admin123', 1)`);
            }
        } finally {
            await connection.close();
        }
        
        const mongoClient = new MongoClient(process.env.MONGO_URI);
        await mongoClient.connect();
        mongoDb = mongoClient.db(process.env.MONGO_DATABASE);
        logsCol = mongoDb.collection('complaint_logs');
        console.log('Oracle & MongoDB ready');
    } catch (e) { console.error('DB Error:', e.message); }
}

app.post('/api/register', async (req, res) => {
    if (!oraclePool) return res.status(500).json({ success: false, message: 'DB not ready' });
    const { name, email, phone, password } = req.body;
    const connection = await oraclePool.getConnection();
    try {
        const result = await connection.execute(
            'INSERT INTO users (name, email, phone, password) VALUES (:1, :2, :3, :4) RETURNING id INTO :5',
            [name, email, phone, password, { type: oracledb.NUMBER, dir: oracledb.BIND_OUT }]
        );
        res.json({ success: true, message: 'Registered', userId: result.outBinds[0][0] });
    } catch (e) {
        res.status(400).json({ success: false, message: 'Email exists' });
    } finally {
        await connection.close();
    }
});

app.post('/api/login', async (req, res) => {
    if (!oraclePool) return res.status(500).json({ success: false, message: 'DB not ready' });
    const { email, password } = req.body;
    const connection = await oraclePool.getConnection();
    try {
        const result = await connection.execute('SELECT * FROM users WHERE email = :email', { email });
        const users = result.rows;
        if (users.length === 0 || users[0].PASSWORD !== password) return res.status(401).json({ success: false, message: 'Invalid' });
        req.session.userId = users[0].ID;
        req.session.isAdmin = users[0].IS_ADMIN;
        req.session.name = users[0].NAME;
        res.json({ success: true, user: { id: users[0].ID, name: users[0].NAME, isAdmin: users[0].IS_ADMIN } });
    } finally {
        await connection.close();
    }
});

app.post('/api/logout', (req, res) => { req.session.destroy(); res.json({ success: true }); });
app.get('/api/user', (req, res) => req.session.userId ? res.json({ success: true, user: { id: req.session.userId, name: req.session.name, isAdmin: req.session.isAdmin } }) : res.status(401).json({ success: false }));

app.post('/api/complaint', async (req, res) => {
    if (!oraclePool || !logsCol) return res.status(500).json({ success: false, message: 'DB not ready' });
    const { title, category, priority, description } = req.body;
    const connection = await oraclePool.getConnection();
    try {
        const result = await connection.execute(
            'INSERT INTO complaints (user_id, title, category, priority, status) VALUES (:1, :2, :3, :4, \'Pending\') RETURNING complaint_id INTO :5',
            [req.session.userId, title, category, priority, { type: oracledb.NUMBER, dir: oracledb.BIND_OUT }]
        );
        await logsCol.insertOne({ complaint_id: result.outBinds[0][0], description, updates: [{ status: 'Pending', date: new Date().toISOString().split('T')[0] }] });
        res.json({ success: true, complaintId: result.outBinds[0][0] });
    } finally {
        await connection.close();
    }
});

app.get('/api/complaints', async (req, res) => {
    if (!oraclePool || !logsCol) return res.status(500).json({ success: false, message: 'DB not ready' });
    const connection = await oraclePool.getConnection();
    try {
        const sql = req.session.isAdmin ? 
            'SELECT c.*, u.name u_name, u.email u_email FROM complaints c JOIN users u ON c.user_id = u.id ORDER BY c.created_at DESC' : 
            'SELECT c.*, u.name u_name, u.email u_email FROM complaints c JOIN users u ON c.user_id = u.id WHERE c.user_id = :userId ORDER BY c.created_at DESC';
        const binds = req.session.isAdmin ? {} : { userId: req.session.userId };
        const result = await connection.execute(sql, binds);
        const complaints = result.rows;
        for (let x of complaints) {
            const l = await logsCol.findOne({ complaint_id: x.COMPLAINT_ID });
            if (l) { x.description = l.description; x.updates = l.updates; }
        }
        res.json({ success: true, complaints });
    } finally {
        await connection.close();
    }
});

app.put('/api/complaint/status', async (req, res) => {
    if (!oraclePool || !logsCol) return res.status(500).json({ success: false, message: 'DB not ready' });
    const { complaintId, status } = req.body;
    const connection = await oraclePool.getConnection();
    try {
        await connection.execute('UPDATE complaints SET status = :status WHERE complaint_id = :complaintId', { status, complaintId });
        await logsCol.updateOne({ complaint_id: parseInt(complaintId) }, { $push: { updates: { status, date: new Date().toISOString().split('T')[0] } } });
        res.json({ success: true });
    } finally {
        await connection.close();
    }
});

app.get('/api/complaint/:id', async (req, res) => {
    if (!oraclePool || !logsCol) return res.status(500).json({ success: false, message: 'DB not ready' });
    const connection = await oraclePool.getConnection();
    try {
        const result = await connection.execute(
            'SELECT c.*, u.name u_name, u.email u_email, u.phone u_phone FROM complaints c JOIN users u ON c.user_id = u.id WHERE c.complaint_id = :id',
            { id: req.params.id }
        );
        const complaints = result.rows;
        if (complaints.length === 0 || (!req.session.isAdmin && complaints[0].USER_ID !== req.session.userId)) return res.status(403).json({ success: false });
        const c = complaints[0];
        const l = await logsCol.findOne({ complaint_id: parseInt(req.params.id) });
        if (l) { c.description = l.description; c.updates = l.updates; }
        res.json({ success: true, complaint: c });
    } finally {
        await connection.close();
    }
});

app.get('/', (r, res) => res.sendFile(__dirname + '/public/index.html'));
app.get('/login', (r, res) => res.sendFile(__dirname + '/public/login.html'));
app.get('/register', (r, res) => res.sendFile(__dirname + '/public/register.html'));
app.get('/dashboard', (r, res) => res.sendFile(__dirname + '/public/dashboard.html'));
app.get('/admin', (r, res) => res.sendFile(__dirname + '/public/admin.html'));

initDB().then(() => app.listen(PORT, () => console.log('Server: http://localhost:' + PORT + ' | Admin: admin@system.com / admin123')));
